name: Go
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
jobs:

  lint:
    name: Lint
    strategy:
      go: [1.12.x, 1.13.x]
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: true
    runs-on: ${{ matrix.platform }}
    steps:

    - name: Install Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      uses: actions/setup-node@v1
      with:
        path: ${{ go.module-path }}

    - name: Get dependencies
      working-directory: ${{ go.module-path }}
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Intsall Golangci-lint 
      run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b . latest

    - name: Lint
      run: ./golangci-lint run ${{ go.module-path }}